apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-param
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  CLUSTER_ENVIRONMENT: dev
  CLUSTER_NAME: dev-vehagn-tg
  DOMAIN_BASE: dev.iseja
  DOMAIN_TLD: net
